#!/usr/bin/env bash
# ==============================================================================
# PROJECT:   SWIFTLLM
# FILE:      docker/airgap/build-airgap.sh
# AUTHOR:    Peter A. Aldrich Jr.
# ------------------------------------------------------------------------------
# Run on a CONNECTED machine to produce a single self-contained tarball that
# installs SwiftLLM (Docker) on an AIR-GAPPED host with no internet access.
#
# Unlike the source air-gap bundle (../../airgap-bundle.sh, which ships wheels +
# Rust), this ships a fully built container image — nothing is compiled or
# downloaded on the target. Just `docker load` and run.
#
# Usage:
#   ./build-airgap.sh                         # Ubuntu GPU image, no model
#   ./build-airgap.sh --os rhel               # RHEL/UBI9 image
#   ./build-airgap.sh --cpu                    # CPU-only image
#   ./build-airgap.sh -m org/repo:file.gguf    # bundle a model too (repeatable)
#   ./build-airgap.sh -o /tmp/bundle.tar.gz    # custom output path
#   ./build-airgap.sh --no-build               # use an already-built image
#
# The bundle contains:
#   image.tar           docker-saved SwiftLLM image
#   models/             (optional) pre-downloaded models
#   compose/            docker-compose files + swiftllmctl + ready .env
#   load-airgap.sh      offline installer (also embedded; see ../load-airgap.sh)
#   README.txt
# Licensed under the Apache License, Version 2.0
# ==============================================================================
set -euo pipefail

C='\033[0;36m'; G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; N='\033[0m'
info(){ echo -e "${C}[airgap-build]${N} $*"; }
ok(){   echo -e "${G}[ok]${N} $*"; }
warn(){ echo -e "${Y}[warn]${N} $*"; }
die(){  echo -e "${R}[fail]${N} $*" >&2; exit 1; }

DOCKER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_DIR="$(cd "$DOCKER_DIR/.." && pwd)"
VERSION_TAG="2.0.0"

OS="ubuntu"; ACCEL="gpu"; OUTPUT=""; NO_BUILD=false; MODELS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --os) OS="$2"; shift 2 ;;
        --cpu) ACCEL="cpu"; shift ;;
        --gpu) ACCEL="gpu"; shift ;;
        -m|--model) MODELS+=("$2"); shift 2 ;;
        -o|--output) OUTPUT="$2"; shift 2 ;;
        --no-build) NO_BUILD=true; shift ;;
        -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) die "Unknown option: $1" ;;
    esac
done

command -v docker >/dev/null 2>&1 || die "docker is required on the build host"

case "$OS" in
    ubuntu) DOCKERFILE="docker/Dockerfile.ubuntu"; PYV="3.10"; IMAGE="swiftllm:ubuntu-${VERSION_TAG}" ;;
    rhel)   DOCKERFILE="docker/Dockerfile.rhel";   PYV="3.11"; IMAGE="swiftllm:rhel-${VERSION_TAG}" ;;
    *) die "Unknown --os '$OS' (ubuntu|rhel)" ;;
esac

FEATURES="cuda"; TORCH_INDEX="https://download.pytorch.org/whl/cu124"
if [[ "$ACCEL" == "cpu" ]]; then
    FEATURES="cpu"; TORCH_INDEX="https://download.pytorch.org/whl/cpu"
    IMAGE="${IMAGE}-cpu"
fi

[[ -z "$OUTPUT" ]] && OUTPUT="$REPO_DIR/swiftllm-docker-airgap-${OS}-$(uname -m).tar.gz"

# ----------------------------------------------------------------------------
# 1. Build the runtime image (unless told to reuse an existing one)
# ----------------------------------------------------------------------------
if $NO_BUILD; then
    docker image inspect "$IMAGE" >/dev/null 2>&1 || die "--no-build set but image '$IMAGE' not found"
    info "Reusing existing image: $IMAGE"
else
    info "Building $IMAGE (target=runtime, features=$FEATURES) — this can take a while..."
    docker build -f "$REPO_DIR/$DOCKERFILE" --target runtime -t "$IMAGE" \
        --build-arg PYTHON_VERSION="$PYV" \
        --build-arg SWIFTLLM_FEATURES="$FEATURES" \
        --build-arg TORCH_INDEX_URL="$TORCH_INDEX" \
        "$REPO_DIR"
    ok "Image built: $IMAGE"
fi

# ----------------------------------------------------------------------------
# 2. Stage the bundle
# ----------------------------------------------------------------------------
STAGE="$(mktemp -d)"; trap 'rm -rf "$STAGE"' EXIT
BUNDLE="$STAGE/swiftllm-docker-airgap"
mkdir -p "$BUNDLE/compose" "$BUNDLE/models"

info "Saving image to tar (this is the big step)..."
docker save "$IMAGE" -o "$BUNDLE/image.tar"
ok "Saved $(du -h "$BUNDLE/image.tar" | cut -f1) image"

# Compose files + control script
cp "$DOCKER_DIR"/docker-compose.yml "$DOCKER_DIR"/docker-compose.cpu.yml "$BUNDLE/compose/"
cp "$DOCKER_DIR"/swiftllmctl "$BUNDLE/compose/"
cp "$DOCKER_DIR/airgap/load-airgap.sh" "$BUNDLE/load-airgap.sh"
chmod +x "$BUNDLE/load-airgap.sh" "$BUNDLE/compose/swiftllmctl"

# A ready-to-use .env pinned to the bundled image (so `up` never tries to build).
cat > "$BUNDLE/compose/.env" <<EOF
# Generated by build-airgap.sh — pinned to the bundled image.
SWIFTLLM_OS=${OS}
SWIFTLLM_IMAGE=${IMAGE}
SWIFTLLM_DOCKERFILE=${DOCKERFILE}
SWIFTLLM_TARGET=runtime
SWIFTLLM_FEATURES=${FEATURES}
SWIFTLLM_MODEL=
SWIFTLLM_HOST=0.0.0.0
SWIFTLLM_PORT=8000
SWIFTLLM_HOST_PORT=8000
SWIFTLLM_MODEL_DIR=/models
NVIDIA_VISIBLE_DEVICES=all
HF_TOKEN=
SWIFTLLM_API_KEY=
EOF

# ----------------------------------------------------------------------------
# 3. (Optional) pre-download models into the bundle
# ----------------------------------------------------------------------------
if [[ ${#MODELS[@]} -gt 0 ]]; then
    info "Pre-downloading ${#MODELS[@]} model(s) into the bundle..."
    GPU_FLAG=(); [[ "$ACCEL" == "gpu" ]] && GPU_FLAG=(--gpus all)
    for m in "${MODELS[@]}"; do
        info "  downloading: $m"
        docker run --rm "${GPU_FLAG[@]}" \
            -v "$BUNDLE/models:/models" -e SWIFTLLM_MODEL_DIR=/models \
            -e HF_TOKEN="${HF_TOKEN:-}" \
            "$IMAGE" swiftllm download -m "$m" \
            || warn "download failed for $m (continuing)"
    done
    # First-run default model for the bundled .env
    sed -i.bak "s|^SWIFTLLM_MODEL=.*|SWIFTLLM_MODEL=${MODELS[0]}|" "$BUNDLE/compose/.env" && rm -f "$BUNDLE/compose/.env.bak"
    ok "Models staged ($(du -sh "$BUNDLE/models" | cut -f1))"
fi

cat > "$BUNDLE/README.txt" <<EOF
SwiftLLM — offline Docker bundle
================================
OS:       ${OS}
Image:    ${IMAGE}
Accel:    ${ACCEL}

INSTALL (on the air-gapped host, Docker required):
  tar xzf $(basename "$OUTPUT")
  cd swiftllm-docker-airgap
  ./load-airgap.sh                # docker load + restore models into a volume

RUN:
  cd compose
  # edit .env (set SWIFTLLM_MODEL if not already), then:
  ./swiftllmctl up
  ./swiftllmctl logs -f
  curl http://localhost:8000/health

GPU hosts need the NVIDIA Container Toolkit pre-installed (offline RPM/DEB).
EOF

# ----------------------------------------------------------------------------
# 4. Pack
# ----------------------------------------------------------------------------
info "Creating archive: $OUTPUT"
( cd "$STAGE" && tar czf "$OUTPUT" swiftllm-docker-airgap )
ok "Bundle ready: $OUTPUT ($(du -h "$OUTPUT" | cut -f1))"
echo
echo "Transfer it to the air-gapped host, extract, and run ./load-airgap.sh"
